version: "3.4"
services:  
  mysql-container:
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - mysql-container:/var/lib/mysql:rw
    image: 'mysql:5.6'
  achat-back:
    depends_on:
      - mysql-container
    container_name: achat-back
    image: amineounissi/my-repo:achat.2.5.9-18    
    ports:
      - "8089:8089"

volumes:
  mysql-container: { }

