version: "3.4"
services:  
  mysql-container:
    container_name: mysql-container
    ports:
      - '3307:3306'
    restart: always
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql-container:/var/lib/mysql:rw
    image: 'mysql:5.6'
    
  achat-back:
    depends_on:
      - mysql-container
    container_name: achat-back
    image: amineounissi/my-repo:achat.$IMAGE_NAME    
    ports:
      - '8090:8089'

volumes:
  mysql-container: { }
