version: "3"
services:
  spring_app:
    image: amineounissi/my-repo:achat.$IMAGE_NAME
    container_name: achat
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:5.6
    restart: unless-stopped
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - /home/mysql/data:/var/lib/mysql

networks:
  springmysql-net:      
