version: "3.4"
services:
  spring_app:
    image: amineounissi/my-repo:achat.$IMAGE_NAME
    container_name: achat-back
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:5.6
    user: root
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_container:/var/lib/mysql:rw

volumes:
  mysql_container: { }
