version: "3.4"
services:  
  mysql-container:
    container_name: mysql-container
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql-container:/var/lib/mysql:rw
    image: 'mysql:5.6'
  achat-back:
    depends_on:
      - mysql-container
    container_name: achat-back
    image: amineounissi/my-repo:achat.2.5.9-47    
    ports:
      - '8089:8089'

volumes:
  mysql-container: { }
