version: "3.4"
services:     
  achat-back:
    depends_on:
      - mysqld
    container_name: achat-back
    image: amineounissi/my-repo:achat.2.5.9-18    
    ports:
      - "8089:8089"

volumes:
  mysqld: { }

