version: "3.4"
services:
  mysql_container:
    container_name: mysql_container
    image: mysql:5.6
    restart: always
    ports:
      - 3307:3307
    networks:
      - springmysql-net
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_container:/var/lib/mysql:rw
      
  achat-back:
    depends_on:
      - mysql_container
    container_name: achat-back
    image: amineounissi/my-repo:achat.2.5.9-18    
    ports:
      - "8089:8089"

    networks:
      - springmysql-net

volumes:
  mysql_container: { }
  
networks:
  springmysql-net:
