version: "3.4"
services:
    mysql_container:
    container_name: mysql_container
    image: mysql:5.6
    user: root
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_container:/var/lib/mysql:rw
      
    achat-back:
    container_name: achat-back
    image: amineounissi/my-repo:achat.$IMAGE_NAME    
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysql_container

volumes:
  mysql_container: { }
